# sync.yml
name: Sync to GitLab
on:
  push:
    branches:
      - main
  delete:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up GitLab CLI
        uses: opensourcegroups/cf-ip-ranges@v1.0.1
        with:
          gitlab_host: ${{ secrets.GITLAB_HOST }}
          gitlab_token: ${{ secrets.GITLAB_TOKEN }}
      - name: Sync to GitLab
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add gitlab ${{ secrets.GITLAB_REPO_URL }}
          git push --force --tags gitlab ${{ github.ref }}
          if [ "${{ github.event_name }}" = "delete" ]; then
            git push --delete gitlab ${{ github.ref }}
          fi
