name: Sync to GitLab
on:
  push:
  delete:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Mirror to GitLab
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ${{ secrets.GITLAB_HOST }}
        ssh_private_key: ${{ secrets.GITLAB_TOKEN }}
        FORCE_PUSH: true
