name: Sync to GitLab
on:
  push:
  delete:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - name: Fetch all history # <-- add this step
      run: git fetch --unshallow origin
    - name: Mirror to GitLab
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ${{ secrets.GITLAB_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        fetch-depth: 0
        force: true
        refs: refs/heads/main
