name: build

on: 
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: xiaomozhang/cf-ip-ranges@master
      with:
        target-url: 'https://gitlab.com/opensourcegroups/cf-ip-ranges.git'
        target-username: 'xiaomozhang'
        target-token: ${{ secrets.GITEE_ACCESS_TOKEN }}
   - name: Run tests
        env:
          ACTIONS_RUNNER_DEBUG: true
