name: Sync GitHub to GitLab
on:
  push:
    branches: [ main ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xiaomozhang/cf-ip-ranges@main
        with:
          destination_repository: git@gitlab.com:opensourcegroups/cf-ip-ranges.git # change this to your GitLab repository SSH URL
          destination_branch_name: main # change this to your GitLab repository branch name
          destination_ssh_key: ${{ secrets.GITEE_ACCESS_TOKEN }} # change this to your GitHub secret name that contains the SSH key
